<h2>Sitemap neu</h2>
<?php if (count($this->sites)): ?>
<table>
  <tr>
    <td>ID</td>
    <td>URL</td>
    <td>Titel</td>
    <td>Lang</td>
    <td>Keywords</td>
    <td>Description</td>
    <td>Robots</td>
    <td>Actions</td>
  </tr>
    <?php foreach ($this->sites as $site):?>
        <tr>
    <td><?php echo $this->escape($site->id); ?></td>
    <td><?php echo $this->escape($site->url); ?></td>
    <td><?php echo $this->escape($site->title); ?></td>
    <td><?php echo $this->escape($site->language); ?></td>
    <td><?php echo $this->escape($site->keyword); ?></td>
    <td><?php echo $this->escape($site->descr); ?></td>
    <td><?php echo $this->escape($site->robots); ?></td>
    <td class="tc last">
      <ul class="actions">
        <li><a href="<?php echo $this->url(array(), 'site-update'). '/' . $site->id ?>">Update</a></li>
        <li><a href="<?php echo $this->url(array(), 'site-delete'). '/' . $site->id ?>">Delete</a></li>
      </ul>
    </td>
  </tr>  
    <?php endforeach; ?>
</table>
<?php else: ?>
No records found - hab nüscht gefunden!!
<?php endif; ?>