<h2>Sitemap</h2>
<?php if (count($this->urls)): ?>
<table>
  <tr>
    <td>ID</td>
    <td>URL</td>
    <?php if (count($this->functionTests)): ?>
        <?php foreach ($this->functionTests as $functionTest):?>
            <td>TestID: <?php echo $this->escape($functionTest->id); ?></td>
        <?php endforeach;?>
    <?php endif;?>
  </tr>
    <?php foreach ($this->urls as $url):?>
  <tr>
        <td><?php echo $this->escape($url->id); ?></td>
        <td><?php echo $this->escape($url->url); ?></td>
        <?php foreach ($this->functionTests as $functionTest):?>
        <?php foreach ($url->functionTests as $test): ?>
            <?php if($test->id === $url->id): ?>
                <?php echo '<td>ID ist gleich</td>';?> 
                <?php else:?>
                <?php echo '<td>nicht gleich</td>';?>
            <?php endif;?>
        <?php endforeach;?>
        <?php endforeach;?>
  </tr>  
    <?php endforeach; ?>
</table>
<?php else: ?>
<p>No records found - hab nüscht gefunden!!</p>
<?php endif;?>